# Generated by Django 4.0 on 2022-02-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Category name')),
                ('description', models.TextField(blank=True, verbose_name='Category descrition')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Product name')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('short_description', models.TextField(blank=True, max_length=60, verbose_name='products short description')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='products description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='products price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity of products available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory')),
            ],
        ),
    ]
