# Generated by Django 4.0 on 2022-03-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0008_alter_shopuser_activation_key_expires'),
        ('mainapp', '0003_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('status', models.PositiveIntegerField(choices=[(1, 'формируется'), (2, 'В обработке'), (3, 'Оплачен'), (4, 'Собирается'), (5, 'Готов'), (6, 'Отменен')], default=1, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.shopuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordersapp.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Продукт')),
            ],
        ),
    ]
