# Generated by Django 3.2.2 on 2022-05-01 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20220419_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 17, 30, 32, 554080, tzinfo=utc), null=True),
        ),
    ]
