# Generated by Django 4.0 on 2022-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='new',
            field=models.TextField(blank=True),
        ),
    ]
