# Generated by Django 4.0 on 2022-02-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_cart_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='new',
        ),
    ]
